models:
  - type: main
    engine: openai
    model: llama-3.1-8b-instant

    parameters:
      base_url: "https://api.groq.com/openai/v1"
      api_key: ""
      
tokenizer:
  type: hf
  name: gpt2


  
  